// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	ENVIRONMENT: "preview";
	DOMAIN: "preview.rvt.app";
	ANALYTICS_TOKEN: "246c9f46859c4532b110bec709213a6a";
	CF_VERSION_METADATA: { id: string; tag: string };
}
