// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	ENVIRONMENT: "preview";
	DOMAIN: "preview.rvt.app";
	CF_VERSION_METADATA: { id: string; tag: string };
}
