name: e2e

runs:
  using: composite
  steps:
    - name: End-to-End
      uses: phi-ag/run-playwright@87679f27e5496a908348a2ba9bd821e59106e2e1 # v1
      with:
        version: v1.61.1-noble@sha256:b48abd6e59fb69b2acfea52553a4d6b0e2530d1bcad15456e6095d6b222dbced
        options: -v ${STORE_PATH}:${STORE_PATH}
        run: |
          corepack enable
          corepack prepare --activate

          pnpm config set store-dir ${STORE_PATH}
          pnpm install --frozen-lockfile

          echo Target ${BASE_URL:-localhost}
          pnpm test:e2e
